apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  labels:
    app: hadwen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadwen
      tier: web-ui
  template:
    metadata:
      labels:
        app: hadwen
        tier: web-ui
    spec:
      containers:
        - image: hadwen/web-ui:0.0.00
          name: web-ui
          imagePullPolicy: "Always"
          ports:
            - containerPort: 443
              protocol: TCP
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          env:
            - name: PORT
              value: "443"
            - name: API_URL
                valueFrom:
                  secretKeyRef:
                    name: api-url
                    key: url
          volumeMounts:
            # name must match the volume name below
            - name: https-certs
              mountPath: /etc/https-certs
      volumes:
        - name: https-certs
          secret:
            secretName: https-certs
