apiVersion: v1
kind: Service
metadata:
  labels:
    app: hadwen
  name: web-ui-service
  namespace: default
spec:
  clusterIP: 10.7.250.202
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30853
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hadwen
    tier: web-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
